[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
hex = "0.4.3"
lazy_static = "0.1.15"
bit-vec = "0.6.3"
openssl = "0.10.38"
rand = "0.8.4"