[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_utils = { path = "../../rust_utils" }
openssl = "0.10.38"
lazy_static = "0.1.15"
rand = "0.8"